echo "Growing Type: ". setValue($_POST['growingType'])."<br>";
echo "Number of acres: ". $acres ."<br>";
echo "Vegtables cultivated: " . $vegetables."<br>";
echo "Orchards cultivated: ". $orchards ."<br>";
echo "Berries cultivated: ". $berries ."<br>";
echo "Vineyards cultivated: ". $vine."<br>";
echo "Herbs cultivated: ". $herb."<br>";
echo "Others cultivated: ". $other ."<br>";
echo "Do you hire people for weeding? ". $_POST['weeding'] ."<br>";
echo "Number of workers hired: ". $_POST['workers'] ."<br>";
echo "Hours total for weeding for workers: ". $_POST['weeklyWorkers'] ."<br>";
echo "Annual budget: $". $budget ."<br>";
echo "Workers expenses: $". $workExpense ."<br>";
echo "Machinery expenses: $". $machineExp ."<br>";
echo "Phytosanitary expenses: $". $pytoExp ."<br>";
echo "Other expenses: $". $otherExp ."<br>";
echo "<br>";